apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-workload
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.spec.destination.namespace }}
  project: {{ .Values.spec.project }}
  source:
    path: "cd/argocd-config/apps-workload"
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
