# Trusted OIDC issuers and certificate identities for cosign keyless verification.
# Replace OWNER/REPO and workflow paths with your actual values.

trusted:
  oidc_issuers:
    - https://token.actions.githubusercontent.com
    - https://github.com/login/oauth
    - https://accounts.google.com
    - https://oidc.eks.eu-central-1.amazonaws.com/id/EXAMPLE1234567890

  identities:
    - https://github.com/alite777/seucure-containter-images/.github/workflows/cosign-verification.yaml@refs/heads/main
    - https://github.com/alite777/seucure-containter-images/.github/workflows/sbom-verification.yaml@refs/heads/main
    - alexander_maximow@web.de
